postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  port: 5432

defaults: &defaults
  pool: 5
  host: localhost
  <<: *postgresql

  # Timeout settings
  timeout: 5000
  reconnect: true
  connect_timeout: 2
  keepalives_idle: 30
  keepalives_interval: 10
  keepalives_count: 2
  checkout_timeout: 5
  reaping_frequency: 10

development:
  <<: *defaults
  database: id-sp-rails_<%= Rails.env %>

test:
  <<: *defaults
  database: id-sp-rails_<%= Rails.env %>

production:
  <<: *defaults
  sslmode: verify-full
  sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
  database: <%= ENV.fetch('DATABASE_NAME') %>
  username: <%= ENV.fetch('DATABASE_USERNAME') %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') %>
