postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  port: 5432

defaults: &defaults
  pool: 5
  timeout: 5000
  host: <%= ENV.fetch('DOCKER_DB_HOST', 'localhost') %>
  username: <%= ENV['DOCKER_DB_USER'] %>

  <<: *postgresql

development:
  <<: *defaults
  database: id-sp-rails_<%= Rails.env %>

test:
  <<: *defaults
  database: id-sp-rails_<%= Rails.env %>

# This whole file is overridden by chef in EC2 environments, so we don't set
# any production values here.
# production:
